version: "2"
services:
  postgres:
    image: postgres
  redis:
    image: redis:3.0.7 # because of bug in qless
  ardoises:
    build: .
    entrypoint: ardoises-server
    ports:
      - "8080:8080"
    links:
      - postgres
      - redis
    logging:
      driver: "json-file"
    environment:
      REDIS_PORT:         "tcp://redis:6379"
      POSTGRES_PORT:      "tcp://postgres:5432"
      POSTGRES_USER:      postgres
      POSTGRES_PASSWORD:  ""
      POSTGRES_DATABASE:  postgres
      DOCKER_USER:        ${DOCKER_USER}
      DOCKER_SECRET:      ${DOCKER_SECRET}
      APPLICATION_ID:     ${APPLICATION_ID}
      APPLICATION_SECRET: ${APPLICATION_SECRET}
      APPLICATION_STATE:  ${APPLICATION_STATE}
      APPLICATION_NAME:   Ardoises
      INTEGRATION_ID:     ${INTEGRATION_ID}
      INTEGRATION_SECRET: ${INTEGRATION_SECRET}
      INTEGRATION_PEM:    ${INTEGRATION_PEM}
