version: "2"
services:
  redis:
    image: redis:alpine
  docker:
    image: shipyard/docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  clean:
    env_file: .environment
    build:
      context: .
      dockerfile: docker/Dockerfile-util-quick
    entrypoint: ardoises-clean
    links:
      - docker
      - redis
    logging:
      driver: "json-file"
    environment:
      DOCKER_URL: "tcp://docker:2375"
      REDIS_URL:  "tcp://redis:6379"
  invitation:
    env_file: .environment
    build:
      context: .
      dockerfile: docker/Dockerfile-util-quick
    entrypoint: ardoises-invitation
    links:
      - redis
    logging:
      driver: "json-file"
    environment:
      REDIS_URL:  "tcp://redis:6379"
  permission:
    env_file: .environment
    build:
      context: .
      dockerfile: docker/Dockerfile-util-quick
    entrypoint: ardoises-permission
    links:
      - redis
    logging:
      driver: "json-file"
    environment:
      REDIS_URL:  "tcp://redis:6379"
  server:
    env_file: .environment
    build:
      context: .
      dockerfile: docker/Dockerfile-server-quick
    entrypoint: ardoises-server
    ports:
      - "8080:80"
    links:
      - docker
      - redis
    logging:
      driver: "json-file"
    environment:
      DOCKER_URL: "tcp://docker:2375"
      REDIS_URL:  "tcp://redis:6379"
