version: "2"
services:
  redis:
    image: redis:alpine
    volumes:
      - ./data:/data
  docker:
    image: shipyard/docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  clean:
    env_file: .environment
    build:
      context: .
      dockerfile: docker/Dockerfile-noresty-quick
    entrypoint: ardoises-clean
  invitation:
    env_file: .environment
    build:
      context: .
      dockerfile: docker/Dockerfile-noresty-quick
    entrypoint: ardoises-invitation
  webhook:
    env_file: .environment
    build:
      context: .
      dockerfile: docker/Dockerfile-noresty-quick
    entrypoint: ardoises-webhook
  ardoises:
    env_file: .environment
    build:
      context: .
      dockerfile: docker/Dockerfile-resty-quick
    entrypoint: ardoises-server
    ports:
      - "8080:8080"
      - "8081:8443"
    volumes:
      - ./static:/static
      - ./src/ardoises:/usr/share/lua/5.1/ardoises
      - ./etc/letsencrypt:/etc/letsencrypt
