version: "2"
services:
  postgres:
    image: postgres
  redis:
    image: redis:3.0.7 # because of bug in qless
  docker:
    image: shipyard/docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  ardoises:
    env_file: .environment
    build:
      context: .
      dockerfile: Dockerfile-quick
    entrypoint: ardoises-server
    ports:
      - "8080:8080"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
    environment:
      DOCKER_PORT:        "tcp://docker:2375"
      REDIS_PORT:         "tcp://redis:6379"
      POSTGRES_PORT:      "tcp://postgres:5432"
      POSTGRES_USER:      postgres
      POSTGRES_PASSWORD:  ""
      POSTGRES_DATABASE:  postgres
      ARDOISES_USER:      ardoises
