version: "2"
services:
  redis:
    image: redis:alpine
  docker:
    image: shipyard/docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  clean:
    env_file: .environment
    build:
      context: .
      dockerfile: docker/Dockerfile-util-quick
    entrypoint: ardoises-clean
    links:
      - docker
      - redis
  invitation:
    env_file: .environment
    build:
      context: .
      dockerfile: docker/Dockerfile-util-quick
    entrypoint: ardoises-invitation
    links:
      - docker
      - redis
  ardoises:
    env_file: .environment
    build:
      context: .
      dockerfile: docker/Dockerfile-server-quick
    entrypoint: ardoises-server
    ports:
      - "8080:80"
    links:
      - docker
      - redis
